# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  strategy:
    parallel: 1
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install
    workingDirectory: HSLDemo/ClientApp  
    displayName: 'npm install'
  - script: npm run build
    workingDirectory: HSLDemo/ClientApp  
    displayName: 'npm build'
    
  - task: ArchiveFiles@2
    inputs:
     rootFolderOrFile: 'HSLDemo/ClientApp/build'
     includeRootFolder: false
     archiveType: zip
     archiveFile: '$(Build.ArtifactStagingDirectory)/frontend/build.zip'
     replaceExistingArchive: true
    displayName: 'archive to zip file'

  - task: PublishBuildArtifacts@1
    inputs: 
     pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
     artifactName: 'frontend'
    displayName: 'publish to pipeline' 